// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVaUTt-CK5hbnsGphXOS5Ups_P_puK-x0',
    appId: '1:815659178274:web:470c982ea0ff3a3a0aed7b',
    messagingSenderId: '815659178274',
    projectId: 'blogapp-1030',
    authDomain: 'blogapp-1030.firebaseapp.com',
    storageBucket: 'blogapp-1030.appspot.com',
    measurementId: 'G-W2KCTLQYW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyO-ZebRMS3j_XxKalm00x8K2Mj8kzOo',
    appId: '1:815659178274:android:aacb667d499221e40aed7b',
    messagingSenderId: '815659178274',
    projectId: 'blogapp-1030',
    storageBucket: 'blogapp-1030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXAPwFU_Mi6CrH-JBryNTJJWLvEfwtCA',
    appId: '1:815659178274:ios:7dd559328f08dd700aed7b',
    messagingSenderId: '815659178274',
    projectId: 'blogapp-1030',
    storageBucket: 'blogapp-1030.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );
}
